### ISSUE TITLE
System UI constantly restarting in Pixel Experience rom

### ISSUE THREAD

**Issue by usamaiqbal1177** [GravityBox/GravityBox#2058]
Hi! Good day, sir.
I'm on latest canary EdXposed YAHFA 4523 build by @MlgmXyysd
Gravity box q is causing system UI to restart constantly. Pixel experience is almost a bare bones rom and is missing many features. Gb is a must. Can u take a log and look what's wrong, please? 
[logs-2020-03-20-20-27-15.zip](https://github.com/GravityBox/GravityBox/files/4374219/logs-2020-03-20-20-27-15.zip)

**Comment by C3C0** [comment]
I cannot see any crashes in the logs provided. Please, capture a logcat during crash.

**Comment by usamaiqbal1177** [comment]
Ok. I'll give logs again with increased logger buffer size

**Comment by C3C0** [comment]
Potentially fixed in 4a0687c42f8b4784373daee98bcd070522293e3b

**Comment by usamaiqbal1177** [comment]
> Potentially fixed in [4a0687c](https://github.com/GravityBox/GravityBox/commit/4a0687c42f8b4784373daee98bcd070522293e3b)

Sir, the new traffic meter in aosp roms still not supported by gravitybox 😢

**Comment by richard-scott** [comment]
@C3C0  Is there an Apk I can test this with?

**Comment by richard-scott** [comment]
> Potentially fixed in [4a0687c](https://github.com/GravityBox/GravityBox/commit/4a0687c42f8b4784373daee98bcd070522293e3b)

This fix seems to work for me on Pixelexperience 😁

**Comment by richard-scott** [comment]
OK, ignore that. It's actually made it worse for me 😢
